### ISSUE TITLE
Minor suggestions

### ISSUE THREAD

**Issue by neurolabusc** [dprice80/mni2fs#1]
Hello-
  This is a great tool. I have two minor suggestions - I have sent commented, patched code to your gmail account.
 1.) The current code requires the Statistics and Machine Learning Toolbox due to a single function 'quantile'. Octave has a similar function that I ported to Matlab. This removes dependency on this proprietary toolbox.
 2.) The current 'run_example' file requires the user to specify the location of the file 'run_example.m', but this can be automatically detected with the call
 toolboxpath = fileparts(which(mfilename));

-c

**Comment by dprice80** [comment]
Thanks for your input, Chris, I have now added a quantile function (I actually used the quantile2.m function since I had it already, and is quite versatile). 

I have not changed run_example, because it is actually not meant to be executed as a function, rather by running individual cells, and in that case mfilename does not work. I do use the function in other parts of my code though.
